all:
	make PROJECT=encrypted_password_database FINAL=1 64BITCFG=1 RHEL=8 -f ../../env/linux.mak

install:
	make PROJECT=encrypted_password_database FINAL=1 64BITCFG=1 RHEL=8 -f ../../env/linux.mak install

clean:
	make PROJECT=encrypted_password_database FINAL=1 64BITCFG=1 RHEL=8 -f ../../env/linux.mak clean

