all:
	make PROJECT=wxappfw FINAL=1 64BITCFG=1 -f ../../env/linux.mak

install:
	make PROJECT=wxappfw FINAL=1 64BITCFG=1 -f ../../env/linux.mak install

clean:
	make PROJECT=wxappfw FINAL=1 64BITCFG=1 -f ../../env/linux.mak clean


